# Generated by Django 5.0.4 on 2024-05-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=100)),
                ('nombre_profesor', models.CharField(max_length=100)),
                ('nombre_materia', models.CharField(max_length=100)),
                ('calificacion_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calificacion_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calificacion_3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('evaluacion_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calificacion_final', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
