# Generated by Django 4.2.13 on 2024-05-20 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alumno_calificaciones_alumno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciones',
            name='user',
        ),
    ]
