# Generated by Django 4.2.13 on 2024-05-20 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profesores'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciones',
            name='profesor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='api.profesores'),
            preserve_default=False,
        ),
    ]
