# Generated by Django 4.2.13 on 2024-05-20 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_calificaciones_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciones',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='calificaciones',
            name='profesor',
        ),
    ]
