# Generated by Django 4.2.13 on 2024-05-21 23:36

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_remove_calificaciones_alumno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciones',
            name='Alumno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.alumno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='Profesor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.profesores'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesores',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')])),
                ('curp', models.CharField(max_length=150, validators=[api.models.validate_curp])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='Control',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.control'),
            preserve_default=False,
        ),
    ]
