# Generated by Django 4.2.13 on 2024-05-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_alumno_calificaciones_alumno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control',
            name='matricula',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='profesores',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesores',
            name='matricula',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
